name: ct312h_project
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  icons_plus: ^5.0.0
  intl: ^0.20.2
  flutter_colorpicker: ^1.1.0
  provider: ^6.1.2

  pocketbase: ^0.22.0
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.2
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
